ChangHyukGod/CodeBlue3

SimpleDms/src/main/java/com/simplecoding/simpledms/config/WebSecurityConfig.java, SimpleDms/src/main/java/com/simplecoding/simpledms/controller/main/TourController.java, SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/main/TourMapper.java, SimpleDms/src/main/java/com/simplecoding/simpledms/service/main/TourService.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/main/Tour.java, SimpleDms/src/main/resources/config/mybatis-config.xml, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/views/auth/LoginView.vue
- Tour테이블 전체조회, 추가, 상세조회 기능 코딩
- 웹시큐리티 경로 접근권한 수정
=> 메인_백엔드_기능1_수정

front/src/router/index.js
=> 메인_프론트_라우터 수정

SimpleDms/src/main/java/com/simplecoding/simpledms/controller/main/TourController.java, SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/main/TourMapper.java, SimpleDms/src/main/java/com/simplecoding/simpledms/service/main/TourService.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/main/Tour.java, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/services/main/MainService.js, front/src/views/main/MainAdd.vue, front/src/views/main/MainView.vue
=> 메인_이미지 업로드

tourdb.txt
=> tour_db.txt.수정

.idea/.gitignore, .idea/CodeBlue3.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml
Remove .idea folder from repository
=> Remove .idea folder from repository

SimpleDms/src/main/java/com/simplecoding/simpledms/controller/main/TourController.java, SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/main/TourMapper.java, SimpleDms/src/main/java/com/simplecoding/simpledms/service/main/TourService.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/main/Tour.java, SimpleDms/src/main/resources/mappers/main/Tour.xml
=> 메인_이미지 업로드 코드수정

front/src/views/main/MainAdd.vue, front/src/views/main/MainUpdate.vue
추가/수정 페이지 파일(사진) 선택 시, 미리보기 코드 추가
=> 메인_추가/수정 페이지 코드수정

front/src/main.js, front/src/services/main/MainService.js, front/src/views/main/MainView.vue
=> MainView 메인 캐러셀 수정

SimpleDms/src/main/java/com/simplecoding/simpledms/controller/main/TourController.java, SimpleDms/src/main/resources/application.properties, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/services/main/MainService.js, front/src/views/main/MainUpdate.vue, front/src/views/main/MainView.vue
xml, Controller, DB접속관련 주소 변경 및 프론트 메인페이지 디자인 코드 수정
=> DB접속 변경에 따른 코드 일부 수정

front/src/router/index.js, front/src/views/recommend/RecommendDetail.vue
도균 1202 진짜 최종이요 도균 1202 진짜 최종이요
=> 도균 1202 진짜 최종이요도균 1202 진짜 최종이요

front/public/index.html
=> 도균 api에러뜨는거 고친거

SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/review/ReviewMapper.java, front/src/views/main/MainView.vue
=> mainView 오류 수정 or Review오류 수정

front/package-lock.json, front/package.json, front/public/index.html, front/src/main.js, front/src/views/payment/PaymentView.vue
=> 카카오 결제api 적용

SimpleDms/src/main/java/com/simplecoding/simpledms/service/faq/TalkService.java
=> backend/ faq/Talkservice 수정

front/src/views/admin/AdminFaqQuestion.vue, front/src/views/recommend/RecommendView.vue
=> 도균 에러 주석막음

front/src/main.js, front/src/views/main/MainView.vue
=> 메인_배너 이동링크 코드수정

front/src/views/payment/CartPaymentView.vue, front/src/views/payment/PaymentView.vue, front/src/views/payment/TotalPayment.vue
=> 3페이지 쿠폰 적용완료

SimpleDms/src/main/resources/mappers/coupon/Coupon.xml, front/src/views/coupon/CouponView.vue
=> 12.10 도균 쿠폰 조금 수정

SimpleDms/src/main/java/com/simplecoding/simpledms/vo/common/Criteria.java, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/components/HeaderCom.vue, front/src/services/main/MainService.js, front/src/views/main/MainView.vue
=> MainView 카테고리/검색 구현

front/package-lock.json, front/package.json, front/src/views/cart/CartView.vue, front/src/views/main/MainDetail.vue, front/src/views/payment/CartPaymentView.vue, front/src/views/payment/PaymentView.vue, front/src/views/payment/TotalPayment.vue
=> 최신 + 디자인 추가/수정

SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/views/main/MainView.vue
=> MainView.vue/Tour.xml 수정

front/src/views/main/MainView.vue
=> MainView.vue 수정

front/src/views/room/UpdateRoomView.vue
=> vue에 타입 변경

front/src/views/main/MainDetail.vue
=> 메인 디테일 외곽선 추가

front/src/views/main/MainView.vue, front/src/views/payment/PaymentView.vue
mainview 오류 수정 및 paymentview 결제 기능 추가
=> mainview 오류 수정 및 paymentview 결제 기능 추가

front/src/views/payment/PaymentView.vue
=> paymentView.vue 수정

SimpleDms/src/main/java/com/simplecoding/simpledms/config/WebSecurityConfig.java, SimpleDms/src/main/java/com/simplecoding/simpledms/controller/coupon/CouponController.java, SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/coupon/CouponMapper.java, SimpleDms/src/main/java/com/simplecoding/simpledms/service/coupon/CouponService.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/comments/Comments.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/common/Criteria.java, SimpleDms/src/main/resources/mappers/comments/Comments.xml, SimpleDms/src/main/resources/mappers/coupon/Coupon.xml, front/src/services/coupon/CounponService.js, front/src/views/coupon/CouponView.vue, front/src/views/main/MainView.vue, front/src/views/mypage/MypageView.vue, front/src/views/payment/PaymentView.vue, front/src/views/recommend/RecommendComAdd.vue, front/src/views/recommend/RecommendComUpdate.vue, front/src/views/recommend/RecommendDetail.vue
=> 커밋안되면 뛰어내림

front/src/views/main/MainView.vue
=> 메인 닫는태그 누락_재업로드

SimpleDms/src/main/resources/mappers/comments/Comments.xml
=> 이것도 커밋부탁드립니다

front/src/views/main/MainView.vue
메인페이지 살짝 수정 및 TOUR 데이터 추가(12개)
=> 메인페이지 살짝 수정 및 TOUR 데이터 추가(12개)

front/src/views/main/MainView.vue
=> 메인페이지_충돌 재업로드

SimpleDms/src/main/java/com/simplecoding/simpledms/controller/main/TourController.java, SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/main/TourMapper.java, SimpleDms/src/main/java/com/simplecoding/simpledms/service/main/TourService.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/common/Criteria.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/main/Tour.java, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/views/main/MainView.vue
메인_COMMENT, POP컬럼 추가 및 Tour백엔드 CRUD코드 수정
=> 메인_COMMENT, POP컬럼 추가 및 Tour백엔드 CRUD코드 수정

SimpleDms/src/main/java/com/simplecoding/simpledms/vo/common/Criteria.java, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/services/main/MainService.js, front/src/views/main/MainView.vue
=> MainView.vue 인기급상승 추가 수정

front/src/views/main/MainView.vue
메인페이지_가격 최저가 코드추가 및 기존 충돌/삭제 코드 수정
=> 메인페이지_가격 최저가 코드추가

SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/main/TourMapper.java, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/App.vue, front/src/views/main/MainView.vue
=> Tour주석추가 및 App.Vue 글씨체 추가임포트

SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/services/main/MainService.js, front/src/views/main/MainAdd.vue, front/src/views/main/MainUpdate.vue
=> 메인_추가/수정 DB컬럼 추가

front/src/views/review/AddReview.vue, front/src/views/review/ReviewDetail.vue, front/src/views/review/ReviewMain.vue
=> 디자인수정-1212최형표

front/src/views/main/MainView.vue
=> 메인페이지 디자인 수정

front/src/views/main/MainView.vue
=> 메인_배너, 추천카드 url수정

SimpleDms/src/main/java/com/simplecoding/simpledms/controller/review/ReviewController.java, SimpleDms/src/main/java/com/simplecoding/simpledms/mapper/review/ReviewMapper.java, SimpleDms/src/main/java/com/simplecoding/simpledms/service/review/ReviewService.java, SimpleDms/src/main/resources/mappers/review/Review.xml, front/src/services/review/ReviewService.js, front/src/views/mypage/MypageView.vue
=> 마이페이지 리뷰글 연동

SimpleDms/src/main/java/com/simplecoding/simpledms/config/WebSecurityConfig.java, SimpleDms/src/main/java/com/simplecoding/simpledms/controller/main/TourController.java, SimpleDms/src/main/java/com/simplecoding/simpledms/vo/main/Tour.java, SimpleDms/src/main/resources/mappers/main/Tour.xml, front/src/components/HeaderCom.vue, front/src/services/main/MainService.js, front/src/views/main/MainAdd.vue, front/src/views/main/MainUpdate.vue
- 투어테이블 컬럼 삭제에 따른 백/프론트 코드수정
- 메인서비스 파일에 로그인 웹토큰 적용
- 페이지별 접근권한 설정 (로그아웃 시 허용 페이지 : 메인, 룸, faq)
=> 메인_로그인 웹토큰 추가

SimpleDms/src/main/java/com/simplecoding/simpledms/config/WebSecurityConfig.java, front/src/services/admin/AdminService.js, front/src/services/cart/CartService.js, front/src/services/recommend/CommentsService.js, front/src/services/review/ReviewService.js, front/src/services/room/RoomService.js, front/src/services/toss/TossService.js
- 로그인 웹토큰 관련 프론트 서비스 파일 코드 추가
- 페이지별 접근권한 수정
=> 로그인 웹토큰 관련 프론트 서비스 파일 코드 추가

SimpleDms/src/main/java/com/simplecoding/simpledms/config/WebSecurityConfig.java, front/src/components/HeaderCom.vue, front/src/views/main/MainView.vue, front/src/views/review/ReviewMain.vue
- 헤더메뉴에 추가 삭제
- 메인뷰 필터 기능 수정 및 전체조회 숙소 제목 데이터 수정
- 로그아웃 시, 리뷰게시판 글등록 버튼 로그인페이지로 강제이동
=> 접근권한 및 프론트 수정

front/src/components/HeaderCom.vue, front/src/services/cart/CartService.js, front/src/services/room/RoomService.js, front/src/views/cart/CartView.vue, front/src/views/room/addRoomPhoto.vue
=> 장바구니에 추가 서비스 수정

front/src/views/review/ReviewDetail.vue, front/src/views/review/ReviewMain.vue
=> ReviewDetail에 상품명추가- 형표

front/src/services/main/MainService.js
=> MainService.js 수정

front/src/components/HeaderCom.vue
=> 로그아웃시 헤더에 짝대기 두줄

front/src/views/cart/CartView.vue, front/src/views/coupon/CouponView.vue
=> 겨울 시즌 할인 쿠폰 삭제

front/src/views/auth/LoginView.vue, front/src/views/auth/RegisterView.vue
=> 회원가입 유효성 검사 + 로그인뷰 디자인
